### ISSUE TITLE
Google Music Manager still shows the original indicator

### ISSUE THREAD

**Issue by harshi3t** [mank319/elementaryPlus#235]

**Comment by cybre** [comment]
Post the output of `ls -R ~/.local/share/sni-qt/icons/`

**Comment by harshi3t** [comment]
/home/harshit/.local/share/sni-qt/icons/google_music_manager:
740a272c66baa9a105e48101377bd5a0.png

**Comment by bil-elmoussaoui** [comment]
Can you post the output of this too ? ```ls -R /tmp/sni-qt_*```

**Comment by harshi3t** [comment]
/tmp/sni-qt_MusicManager_19688-PqOn06:
icons

/tmp/sni-qt_MusicManager_19688-PqOn06/icons:
hicolor

/tmp/sni-qt_MusicManager_19688-PqOn06/icons/hicolor:
16x16

/tmp/sni-qt_MusicManager_19688-PqOn06/icons/hicolor/16x16:
apps

/tmp/sni-qt_MusicManager_19688-PqOn06/icons/hicolor/16x16/apps:
MusicManager_19688_740a272c66baa9a105e48101377bd5a0.png

**Comment by cybre** [comment]
Please update your system if you've installed elementary+ from the PPA or `git pull` if you've cloned the repo and run the installer again.

**Comment by bil-elmoussaoui** [comment]
@harshi3t That's really wired, which version of ```sni-qt``` you're using? ```dpkg -l | grep sni-qt```

**Comment by cybre** [comment]
@bil-elmoussaoui It's a bug I've fixed in #230.

**Comment by bil-elmoussaoui** [comment]
@cybre i see :+1:

**Comment by cybre** [comment]
Please close the issue if it worked.

**Comment by harshi3t** [comment]
I don't know what the problem is. I reinstalled music manager but the problem still persists. Probably has something to do with the fact that I'm starting it with proxychains.

**Comment by cybre** [comment]
Did you reinstall Music Manager or did you re-enable it in the elementary+ Configurator?

**Comment by cybre** [comment]
Sorry, I forgot to replace a variable when I was fixing the original issue. It is fixed now. You can `git pull` to get the fix or you can just rename the icon directory like this:
`mv /home/harshit/.local/share/sni-qt/icons/google_music_manager /home/harshit/.local/share/sni-qt/icons/MusicManager`

**Comment by harshi3t** [comment]
yeah I just came here to say the exact thing !! :D

**Comment by cybre** [comment]
So, fixed now?

**Comment by harshi3t** [comment]
yes it's working.
